### ISSUE TITLE
Can't compile the receive sample code

### ISSUE THREAD

**Issue by markchen1024** [francibm97/UM3750#1]
`C:\Users\fqche\Documents\Arduino\sketch_nov06c\sketch_nov06c.ino: In function 'void loop()':

sketch_nov06c:11: error: no matching function for call to 'UM3750::Code::Code()'

     UM3750::Code code;

                  ^

C:\Users\fqche\Documents\Arduino\sketch_nov06c\sketch_nov06c.ino:11:18: note: candidates are:

In file included from C:\Users\fqche\Documents\Arduino\sketch_nov06c\sketch_nov06c.ino:1:0:

C:\Users\fqche\Documents\Arduino\libraries\UM3750-master\src/UM3750.h:52:3: note: UM3750::Code::Code(int, float)

   Code(int value, float symbolDurationTime) {

   ^

C:\Users\fqche\Documents\Arduino\libraries\UM3750-master\src/UM3750.h:52:3: note:   candidate expects 2 arguments, 0 provided

C:\Users\fqche\Documents\Arduino\libraries\UM3750-master\src/UM3750.h:48:3: note: UM3750::Code::Code(int)

   Code(int value) {

   ^

C:\Users\fqche\Documents\Arduino\libraries\UM3750-master\src/UM3750.h:48:3: note:   candidate expects 1 argument, 0 provided

C:\Users\fqche\Documents\Arduino\libraries\UM3750-master\src/UM3750.h:44:9: note: constexpr UM3750::Code::Code(const UM3750::Code&)

  struct Code {

         ^

C:\Users\fqche\Documents\Arduino\libraries\UM3750-master\src/UM3750.h:44:9: note:   candidate expects 1 argument, 0 provided

C:\Users\fqche\Documents\Arduino\libraries\UM3750-master\src/UM3750.h:44:9: note: constexpr UM3750::Code::Code(UM3750::Code&&)

C:\Users\fqche\Documents\Arduino\libraries\UM3750-master\src/UM3750.h:44:9: note:   candidate expects 1 argument, 0 provided

sketch_nov06c:24: error: 'um3750' was not declared in this scope

     um3750.resetReceivedCode();

     ^`

**Comment by markchen1024** [comment]
Hi francibm97, should I initialize the struct `code` with some arguments?
Is `um3750` equals to `myUM3750`?
Cheers

**Comment by francibm97** [comment]
Sorry for the late response.

 - Regarding the `code`  object: yes, it does not have an empty constructor so you cannot instantiate it that way; on the other hand, it would't make much sense to instantiate it with a random number other than overcoming the compile error
 - The `um3750` was actually a typo for `myUM3750`

I'm sorry for those mistakes and I thank you for pointing them out, I'm updating the readme with a working example.

Bye
